version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: task-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 2002040111Vu
      MYSQL_DATABASE: taskmanager
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5

  taskmanager:
    build: .
    container_name: task-app
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/taskmanager
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 2002040111Vu

volumes:
  mysql_data:
